services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                ENVIRONMENT: ${ENVIRONMENT:-PRODUCTION}
                PORT: ${PORT:-50051}
        image: passeriformub/nukeship:latest
        ports:
            - 50051:${PORT:-50051}
