services:
    server:
        build:
            context: .
            dockerfile: server.Dockerfile
        environment:
            ENVIRONMENT: ${ENVIRONMENT:-PRODUCTION}
        ports:
            - ${PORT}:8080

    client:
        build:
            context: .
            dockerfile: native.Dockerfile
        environment:
            HOST: ${HOST:-localhost}
            SERVER_PORT: ${PORT}
            ENVIRONMENT: ${ENVIRONMENT:-PRODUCTION}
        depends_on: [server]
        ports:
            - 80:80
