services:
    server:
        build:
            context: .
            dockerfile: server.Dockerfile
        environment:
            ENVIRONMENT: ${ENVIRONMENT:-PRODUCTION}
        ports:
            - ${PORT:-80}:8080

    client:
        build:
            context: .
            dockerfile: web.Dockerfile
        environment:
            HOST: ${HOST:-0.0.0.0}
            SERVER_PORT: ${PORT:-80}
            ENVIRONMENT: ${ENVIRONMENT:-PRODUCTION}
        depends_on: [server]
        ports:
            - 80:3000
