import { RawDataStream } from "@game/tree"

export const ExampleFS: RawDataStream = {
    label: "NT",
    sentinel: true,
    shield: 10,
    power: 20,
    rechargeRate: 5,
    children: [
        {
            label: "C:",
            sentinel: true,
            shield: 10,
            power: 20,
            rechargeRate: 5,
            children: [
                {
                    label: "Windows",
                    sentinel: false,
                    shield: 10,
                    power: 20,
                    rechargeRate: 5,
                    children: [
                        {
                            label: "System32",
                            sentinel: false,
                            shield: 10,
                            power: 20,
                            rechargeRate: 5,
                            children: [
                                {
                                    label: "Microsoft",
                                    sentinel: false,
                                    shield: 10,
                                    power: 20,
                                    rechargeRate: 5,
                                    children: [
                                        {
                                            label: "Azure",
                                            sentinel: false,
                                            shield: 10,
                                            power: 20,
                                            rechargeRate: 5,
                                            children: [
                                                {
                                                    label: "Device.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "Preface.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "AzureAD.exe",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                            ],
                                        },
                                        {
                                            label: "Defender",
                                            sentinel: false,
                                            shield: 10,
                                            power: 20,
                                            rechargeRate: 5,
                                            children: [
                                                {
                                                    label: "Defense.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "NoDefense.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "TestingKPS.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                            ],
                                        },
                                    ],
                                },
                                {
                                    label: "Avast",
                                    sentinel: false,
                                    shield: 10,
                                    power: 20,
                                    rechargeRate: 5,
                                    children: [
                                        {
                                            label: "Azure",
                                            sentinel: false,
                                            shield: 10,
                                            power: 20,
                                            rechargeRate: 5,
                                            children: [
                                                {
                                                    label: "Device.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "Preface.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "AzureAD.exe",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                            ],
                                        },
                                        {
                                            label: "Defender",
                                            sentinel: false,
                                            shield: 10,
                                            power: 20,
                                            rechargeRate: 5,
                                            children: [
                                                {
                                                    label: "Defense.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "NoDefense.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "TestingKPS.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                            ],
                                        },
                                    ],
                                },
                                {
                                    label: "Tiberius",
                                    sentinel: false,
                                    shield: 10,
                                    power: 20,
                                    rechargeRate: 5,
                                    children: [
                                        {
                                            label: "Azure",
                                            sentinel: false,
                                            shield: 10,
                                            power: 20,
                                            rechargeRate: 5,
                                            children: [
                                                {
                                                    label: "Device.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "Preface.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "AzureAD.exe",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                            ],
                                        },
                                        {
                                            label: "Defender",
                                            sentinel: false,
                                            shield: 10,
                                            power: 20,
                                            rechargeRate: 5,
                                            children: [
                                                {
                                                    label: "Defense.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "NoDefense.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "TestingKPS.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                            ],
                                        },
                                    ],
                                },
                                {
                                    label: "Taurus",
                                    sentinel: false,
                                    shield: 10,
                                    power: 20,
                                    rechargeRate: 5,
                                    children: [
                                        {
                                            label: "Azure",
                                            sentinel: false,
                                            shield: 10,
                                            power: 20,
                                            rechargeRate: 5,
                                            children: [
                                                {
                                                    label: "Device.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "Preface.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "AzureAD.exe",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                            ],
                                        },
                                        {
                                            label: "Defender",
                                            sentinel: false,
                                            shield: 10,
                                            power: 20,
                                            rechargeRate: 5,
                                            children: [
                                                {
                                                    label: "Defense.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                                {
                                                    label: "NoDefense",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [
                                                        {
                                                            label: "Avast",
                                                            sentinel: false,
                                                            shield: 10,
                                                            power: 20,
                                                            rechargeRate: 5,
                                                            children: [
                                                                {
                                                                    label: "Azure",
                                                                    sentinel: false,
                                                                    shield: 10,
                                                                    power: 20,
                                                                    rechargeRate: 5,
                                                                    children: [
                                                                        {
                                                                            label: "Device.dll",
                                                                            sentinel: false,
                                                                            shield: 10,
                                                                            power: 20,
                                                                            rechargeRate: 5,
                                                                            children: [],
                                                                        },
                                                                        {
                                                                            label: "Preface.dll",
                                                                            sentinel: false,
                                                                            shield: 10,
                                                                            power: 20,
                                                                            rechargeRate: 5,
                                                                            children: [],
                                                                        },
                                                                        {
                                                                            label: "AzureAD.exe",
                                                                            sentinel: false,
                                                                            shield: 10,
                                                                            power: 20,
                                                                            rechargeRate: 5,
                                                                            children: [],
                                                                        },
                                                                    ],
                                                                },
                                                                {
                                                                    label: "Defender",
                                                                    sentinel: false,
                                                                    shield: 10,
                                                                    power: 20,
                                                                    rechargeRate: 5,
                                                                    children: [
                                                                        {
                                                                            label: "Defense.dll",
                                                                            sentinel: false,
                                                                            shield: 10,
                                                                            power: 20,
                                                                            rechargeRate: 5,
                                                                            children: [],
                                                                        },
                                                                        {
                                                                            label: "NoDefense.dll",
                                                                            sentinel: false,
                                                                            shield: 10,
                                                                            power: 20,
                                                                            rechargeRate: 5,
                                                                            children: [],
                                                                        },
                                                                        {
                                                                            label: "TestingKPS.dll",
                                                                            sentinel: false,
                                                                            shield: 10,
                                                                            power: 20,
                                                                            rechargeRate: 5,
                                                                            children: [],
                                                                        },
                                                                    ],
                                                                },
                                                            ],
                                                        },
                                                    ],
                                                },
                                                {
                                                    label: "TestingKPS.dll",
                                                    sentinel: false,
                                                    shield: 10,
                                                    power: 20,
                                                    rechargeRate: 5,
                                                    children: [],
                                                },
                                            ],
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            label: "D:",
            sentinel: false,
            shield: 10,
            power: 20,
            rechargeRate: 5,
            children: [
                {
                    label: "Dev",
                    sentinel: false,
                    shield: 10,
                    power: 20,
                    rechargeRate: 5,
                    children: [
                        {
                            label: "api.dll",
                            sentinel: false,
                            shield: 10,
                            power: 20,
                            rechargeRate: 5,
                            children: [],
                        },
                    ],
                },
            ],
        },
        {
            label: "E:",
            sentinel: false,
            shield: 10,
            power: 20,
            rechargeRate: 5,
            children: [
                {
                    label: "Dev",
                    sentinel: false,
                    shield: 10,
                    power: 20,
                    rechargeRate: 5,
                    children: [
                        {
                            label: "api.dll",
                            sentinel: false,
                            shield: 10,
                            power: 20,
                            rechargeRate: 5,
                            children: [],
                        },
                    ],
                },
            ],
        },
        {
            label: "F:",
            sentinel: false,
            shield: 10,
            power: 20,
            rechargeRate: 5,
            children: [
                {
                    label: "Dev",
                    sentinel: false,
                    shield: 10,
                    power: 20,
                    rechargeRate: 5,
                    children: [
                        {
                            label: "api.dll",
                            sentinel: false,
                            shield: 10,
                            power: 20,
                            rechargeRate: 5,
                            children: [],
                        },
                    ],
                },
            ],
        },
    ],
}
