name: Master
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: ./go.mod

            - name: Install dependencies
              run: go mod tidy

            - name: Set up Docker Compose
              uses: docker/setup-buildx-action@v3

            - name: Build and Run Server
              run: |
                  docker compose up --build --force-recreate --remove-orphans -d server
