name: Master
on:
    push:
        branches:
            - master

jobs:
    build-server:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        env:
            OUT_PATH: ${{ github.workspace }}/pkg/server/bin/Server
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: ./go.mod

            # - name: Refresh protobuf definitions

            - name: Generate code
              run: go generate -x ./...

            - name: Build server
              working-directory: pkg/server
              run: go build -o ${{ env.OUT_PATH }}
