name: PR
on:
    pull_request:
        branches:
            - "*"

jobs:
    build-server:
        runs-on: ubuntu-latest

        # TODO: Add binaries for PRs and upload artifact.
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: ./go.mod

            - name: Install dependencies
              run: go mod tidy

            - name: Run tests
              run: go test ./...

            - name: Lint code
              uses: golangci/golangci-lint-action@v6
              with:
                  version: latest

    build-binaries:
        strategy:
            fail-fast: false
            matrix:
                build:
                    - platform: linux/amd64
                      os: ubuntu-latest
                      name: NukeShip
                    - platform: windows/amd64
                      os: windows-latest
                      name: NukeShip.exe
                    - platform: darwin/universal
                      os: macos-latest
                      name: NukeShip
        runs-on: ${{ matrix.build.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Generate code
              run: go generate ./...

            - name: Create binary
              uses: dAppServer/wails-build-action@main
              with:
                  app-working-directory: ${{ github.workspace }}/pkg/client
                  build-obfuscate: true
                  build-name: ${{ matrix.build.name }}
                  build-platform: ${{ matrix.build.platform }}
