name: Release
on:
    push:
        tags:
            - "*"

jobs:
    release-server:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Compose
              uses: docker/setup-buildx-action@v3

            - name: Build And Tag Image
              run: |
                  docker compose up --build --force-recreate --remove-orphans -d server
                  docker tag passeriformub/nukeship:latest passeriformub/nukeship:${{ github.ref_name }}

            - name: Publish Docker Image
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push Docker Image to Docker Hub
              run: |
                  docker push passeriformub/nukeship:${{ github.ref_name }}
                  docker push passeriformub/nukeship:latest

    release-binaries:
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: NukeShip
                      os: ubuntu-latest
                      platform: linux/amd64
                    - name: NukeShip.exe
                      os: windows-latest
                      platform: windows/amd64
                    - name: nukeship
                      os: macos-latest
                      platform: darwin/universal
        runs-on: ${{ matrix.os }}
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: ./go.mod

            # - name: Refresh protobuf definitions

            - name: Generate code
              run: go generate ./...

            - name: Create binary
              uses: passeriform/wails-build-action@main
              with:
                  app-working-directory: ${{ github.workspace }}/pkg/client
                  build-obfuscate: true
                  build-name: ${{ matrix.name }}
                  build-platform: ${{ matrix.platform }}
                  macos-artifact-name: "NukeShip"
