name: Release
on:
    push:
        tags:
            - "*"

jobs:
    release-binaries:
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: NukeShip
                      os: ubuntu-latest
                      platform: linux/amd64
                    - name: NukeShip.exe
                      os: windows-latest
                      platform: windows/amd64
                    - name: nukeship
                      os: macos-latest
                      platform: darwin/universal
        runs-on: ${{ matrix.os }}
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: ./go.mod

            # - name: Refresh protobuf definitions

            - name: Generate code
              run: go generate -x ./...

            - name: Release binary
              uses: passeriform/wails-build-action@main
              with:
                  app-working-directory: pkg/client
                  build-obfuscate: true
                  build-name: ${{ matrix.name }}
                  build-platform: ${{ matrix.platform }}
                  macos-artifact-name: "NukeShip"
                  wails-version: v2.9.2

    release-notes:
        runs-on: ubuntu-latest
        needs: release-binaries
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Prepare release notes
              run: |
                  chmod +x scripts/*
                  ./scripts/changelog_gen.sh ${{ github.ref_name }} > RELEASE.md

            - name: Update release notes
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh release edit ${{ github.ref_name }} --notes-file RELEASE.md
