name: Release
on:
    push:
        tags:
            - "*"

jobs:
    release-server:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Compose
              uses: docker/setup-buildx-action@v3

            - name: Build And Tag Image
              run: |
                  docker compose up --build --force-recreate --remove-orphans -d server
                  docker tag passeriformub/nukeship:latest passeriformub/nukeship:${{ github.ref_name }}

            - name: Publish Docker Image
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push Docker Image to Docker Hub
              run: |
                  docker push passeriformub/nukeship:${{ github.ref_name }}
                  docker push passeriformub/nukeship:latest

    release-binaries:
        strategy:
            fail-fast: false
            matrix:
                build:
                    - platform: linux/amd64
                      os: ubuntu-latest
                      name: NukeShip
                    - platform: windows/amd64
                      os: windows-latest
                      name: NukeShip.exe
                    - platform: darwin/universal
                      os: macos-latest
                      name: NukeShip
        runs-on: ${{ matrix.build.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create binary
              uses: dAppServer/wails-build-action@v2.2
              with:
                  build-name: ${{ matrix.build.name }}
                  build-platform: ${{ matrix.build.platform }}
