name: Release
on:
    push:
        tags:
            - "*"

jobs:
    release-binaries:
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: NukeShip
                      os: ubuntu-latest
                      platform: linux/amd64
                    - name: NukeShip.exe
                      os: windows-latest
                      platform: windows/amd64
                    - name: nukeship
                      os: macos-latest
                      platform: darwin/universal
        runs-on: ${{ matrix.os }}
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: ./go.mod

            # - name: Refresh protobuf definitions

            - name: Generate code
              run: go generate ./...

            - name: Release binary
              id: release
              uses: passeriform/wails-build-action@main
              with:
                  app-working-directory: pkg/client
                  build-obfuscate: true
                  build-name: ${{ matrix.name }}
                  build-platform: ${{ matrix.platform }}
                  macos-artifact-name: "NukeShip"

        outputs:
            release-id: ${{ steps.release.outputs.release-id }}

    release-notes:
        runs-on: ubuntu-latest
        needs: release-binaries
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Prepare release notes
              id: prepare
              working-directory: ${{ github.workspace }}/scripts
              run: |
                  chmod +x *
                  echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
                  echo "$(./changelog_gen.sh ${{ github.ref_name }})" >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            - name: Test Release Notes
              run: echo ${{ steps.prepare.outputs.RELEASE_NOTES }}

            - name: Update release notes
              uses: irongut/editrelease@v1.2.0
              with:
                  id: ${{ needs.release-binaries.outputs.release-id }}
                  token: ${{ github.token }}
                  replacebody: true
                  name: ${{ github.ref_name }}
                  body: ${{ steps.prepare.outputs.RELEASE_NOTES }}
